### ISSUE TITLE
V6 Roadmap

### ISSUE THREAD

**Issue by twlite** [neplextech/canvacord#160]
- [ ] polyfill previous APIs
- [ ] create templates and templating api
- [ ] create nodes for text, image, shapes rendering

#### ImageManipulation
- Allow chaining multiple methods

```js
const result = await method1()
  .method2()
  .method3()
  .encode(format?);
```
